[env:proton]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#develop
board = rpipico2
framework = picosdk
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200

build_flags =
    -DUSE_TINYUSB=1
    -DCFG_TUSB_MCU=OPT_MCU_RP2350
    -DPICO_STDIO_USB=0
    -DCFG_TUD_HID=1                 # Already in tusb_config.h, but reinforce
    -DCFG_TUD_ENABLED=1             # Force TinyUSB device stack
    -Wl,--whole-archive -ltinyusb_device -Wl,--no-whole-archive